spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sampledb?characterEncoding=UTF-8&serverTimezone=UTC
    username: icalus
    password: retona